apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: recipe-app
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: doesnotmatter
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          name: gke-ingress