# issuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: recipe-app
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: doesnotmatter
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          name: gke-ingress