apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recipe-app
  name: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:  # Moved template field to the correct position
    metadata:
    # namespace: recipe-app
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-pass
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-dbname
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  namespace: recipe-app
  labels:
    app: postgres # Labels and Selectors
spec:
  selector:
    app: postgres
  # type: NodePort # Sets service type
  ports:
    - protocol: TCP
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432