name: destroy

on:
  workflow_dispatch:

env:
    BUCKET_NAME: ${{ vars.BUCKET_NAME }}
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
    CLUSTER_STATIC_IP: ${{ vars.CLUSTER_STATIC_IP }}

    # terraform vars
    TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}

    # auth vars
    CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
    GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    CLUSTER_REGION: ${{ secrets.REGION }}

jobs:
  destroy-terraform-resources:
    name: 'Destroy tf'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GOOGLE_CREDENTIALS }}'
    
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: "destroy cloudflare dns records"
        id: 'tf-cloudflare'
        run: |
          export TF_VAR_service_ip=$(kubectl get ing -n recipe-app | grep 'recipe' | awk '{print $4}')
          terraform init -backend-config="bucket=${{ env.BUCKET_NAME }}"
          terraform destroy -auto-approve -input=false -lock=false
      - name: "destroy cluster global ip"
        run: |
          gcloud compute addresses delete ${{ env.CLUSTER_STATIC_IP }} --global -q
